// flow-typed signature: 0f06b5364ac0a062336d84701b6c61be
// flow-typed version: <<STUB>>/angles_v0.2.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'angles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'angles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'angles/angles' {
  declare module.exports: any;
}

declare module 'angles/angles.min' {
  declare module.exports: any;
}

declare module 'angles/externs' {
  declare module.exports: any;
}

declare module 'angles/gulpfile' {
  declare module.exports: any;
}

declare module 'angles/tests/angles.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'angles/angles.js' {
  declare module.exports: $Exports<'angles/angles'>;
}
declare module 'angles/angles.min.js' {
  declare module.exports: $Exports<'angles/angles.min'>;
}
declare module 'angles/externs.js' {
  declare module.exports: $Exports<'angles/externs'>;
}
declare module 'angles/gulpfile.js' {
  declare module.exports: $Exports<'angles/gulpfile'>;
}
declare module 'angles/tests/angles.test.js' {
  declare module.exports: $Exports<'angles/tests/angles.test'>;
}
