// flow-typed signature: 999ca4e73ed5049556497841b496f09c
// flow-typed version: <<STUB>>/gulp-sass_v^3.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-sass/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-sass/index' {
  declare module.exports: $Exports<'gulp-sass'>;
}
declare module 'gulp-sass/index.js' {
  declare module.exports: $Exports<'gulp-sass'>;
}
declare module 'gulp-sass/test.js' {
  declare module.exports: $Exports<'gulp-sass/test'>;
}
