// flow-typed signature: 7d05280c8d94537e73bd0853456b3af6
// flow-typed version: <<STUB>>/random-weighted-choice_v0.1.3/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-weighted-choice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-weighted-choice' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-weighted-choice/lib/random-weighted-choice' {
  declare module.exports: any;
}

declare module 'random-weighted-choice/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-weighted-choice/lib/random-weighted-choice.js' {
  declare module.exports: $Exports<'random-weighted-choice/lib/random-weighted-choice'>;
}
declare module 'random-weighted-choice/test/test.js' {
  declare module.exports: $Exports<'random-weighted-choice/test/test'>;
}
