// flow-typed signature: cf33449b9d38407cc88b416ce0c87eec
// flow-typed version: <<STUB>>/rpgparameter_v2.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rpgparameter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rpgparameter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rpgparameter/examples/mixin-parameters' {
  declare module.exports: any;
}

declare module 'rpgparameter/lib/aggregators' {
  declare module.exports: any;
}

declare module 'rpgparameter/lib/utils' {
  declare module.exports: any;
}

declare module 'rpgparameter/public/tests' {
  declare module.exports: any;
}

declare module 'rpgparameter/test/index' {
  declare module.exports: any;
}

declare module 'rpgparameter/test/lib/aggregators' {
  declare module.exports: any;
}

declare module 'rpgparameter/test/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rpgparameter/examples/mixin-parameters.js' {
  declare module.exports: $Exports<'rpgparameter/examples/mixin-parameters'>;
}
declare module 'rpgparameter/index' {
  declare module.exports: $Exports<'rpgparameter'>;
}
declare module 'rpgparameter/index.js' {
  declare module.exports: $Exports<'rpgparameter'>;
}
declare module 'rpgparameter/lib/aggregators.js' {
  declare module.exports: $Exports<'rpgparameter/lib/aggregators'>;
}
declare module 'rpgparameter/lib/utils.js' {
  declare module.exports: $Exports<'rpgparameter/lib/utils'>;
}
declare module 'rpgparameter/public/tests.js' {
  declare module.exports: $Exports<'rpgparameter/public/tests'>;
}
declare module 'rpgparameter/test/index.js' {
  declare module.exports: $Exports<'rpgparameter/test/index'>;
}
declare module 'rpgparameter/test/lib/aggregators.js' {
  declare module.exports: $Exports<'rpgparameter/test/lib/aggregators'>;
}
declare module 'rpgparameter/test/lib/utils.js' {
  declare module.exports: $Exports<'rpgparameter/test/lib/utils'>;
}
