const keymirror = require('keymirror');


const ACTION_TYPES = keymirror({
  ALTER_PROGRESS: null,
  ALTER_TECHNICAL_DEBT: null,
  EXCHANGE_COIN_LOCATIONS: null,
  NOOP: null,
  TICK: null,
});

const COIN_TYPES = keymirror({
  TEN: null,
  FIFTY: null,
  HUNDRED: null,
});

const PARAMETERS = {
  BATTLE_BOARD_COLUMN_LENGTH: 7,
  BATTLE_BOARD_ROW_LENGTH: 9,
  MAX_PROGRESS: 100,
  MAX_TECHNICAL_DEBT: 100,
  MIN_PROGRESS: 0,
  MIN_TECHNICAL_DEBT: 0,
  RECRUITMENT_BOARD_COLUMN_LENGTH: 7,
  RECRUITMENT_BOARD_ROW_LENGTH: 2,
};

const STYLES = {
  SQUARE_HEIGHT: 48,
  SQUARE_WIDTH: 48,
};

module.exports = {
  ACTION_TYPES,
  STYLES,
  PARAMETERS,
};
